export const MEMBER_CATEGORIES = [
  // Actually in use across existing member profiles.
  "Finance & Accounting",
  "Engineering & Property",
  "Health & Wellness",
  "Governance & Skills",
  "Insurance & Risk",
  "Leadership",
  "Legal & Governance",
  "Sales & Marketing",
  "Services & Operations",
  "Technology & Business",
  "Creatives & Designers",
  "Entrepreneurs",
  // Not yet used by any member, kept as options for new categories of member.
  "Psychologists",
  "Coaches",
  "Attorneys",
  "Accountants",
  "Property Specialists",
  "Financial Advisors",
  "Medical Professionals",
  "Educators",
  "Marketing & PR",
  "Technology & Digital",
  "Consultants",
  "Healthcare & Wellness",
  "Hospitality & Events",
  "Retail & Fashion",
  "Construction & Trades",
  "Non Profit & Community",
  "Students",
  "Other",
] as const;
