/**
 * Client-side PDF generator for a member's stamped membership agreement —
 * the record made downloadable once the committee verifies proof of
 * payment. Signature is the typed name only: per the agreement's own
 * Clause 7, the typed name is what constitutes the e-signature under the
 * ECT Act; the drawn signature is a UI-only visual aid and isn't persisted.
 */
const AWIN_HEADER = {
  name: "A-Win",
  tagline: "African Women Investment Network",
};

function drawHeader(pdf: import("jspdf").jsPDF, title: string) {
  const pageW = pdf.internal.pageSize.getWidth();
  pdf.setFillColor(61, 139, 47);
  pdf.rect(0, 0, pageW, 60, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.text(AWIN_HEADER.name, 40, 28);
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.text(AWIN_HEADER.tagline, 40, 44);
  pdf.setTextColor(20, 20, 20);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(16);
  pdf.text(title, 40, 90);
  pdf.setDrawColor(232, 150, 10);
  pdf.setLineWidth(1.5);
  pdf.line(40, 100, pageW - 40, 100);
}

function drawFooter(pdf: import("jspdf").jsPDF) {
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  pdf.setFontSize(7.5);
  pdf.setTextColor(120, 120, 120);
  pdf.setFont("helvetica", "normal");
  pdf.text("Generated by the A-Win member portal — a certified copy is kept on file.", 40, pageH - 24);
}

function field(
  pdf: import("jspdf").jsPDF,
  label: string,
  value: string,
  x: number,
  y: number,
  maxWidth: number,
): number {
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  pdf.setTextColor(90, 90, 90);
  pdf.text(label.toUpperCase(), x, y);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(20, 20, 20);
  const lines = pdf.splitTextToSize(value || "—", maxWidth);
  pdf.text(lines, x, y + 14);
  return y + 14 + lines.length * 13 + 8;
}

/** First 6 + last 2 digits, matching the on-screen masking. */
function maskId(id: string) {
  const clean = (id || "").replace(/\s+/g, "");
  if (clean.length < 8) return "•••••••••••••";
  return `${clean.slice(0, 6)} ••••• ${clean.slice(-2)}`;
}

export async function buildMembershipAgreementPdf(input: {
  fullName: string;
  idNumber: string;
  phone: string;
  occupation: string;
  motivation: string;
  contribution: "R200 entry fee" | "R500 monthly";
  agreementVersion: string;
  reference: string;
  typedSignature: string;
  docHash: string;
  dateStr: string;
}): Promise<Blob> {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ orientation: "p", unit: "pt", format: "a4", compress: true });
  const pageW = pdf.internal.pageSize.getWidth();
  const margin = 40;
  const colW = pageW - margin * 2;
  const colHalf = (colW - 20) / 2;

  drawHeader(pdf, "Membership Registration Certificate");
  let y = 130;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(90, 90, 90);
  pdf.text(`Reference: ${input.reference}`, margin, y);
  y += 24;

  const rowY1 = y;
  field(pdf, "Full legal name", input.fullName, margin, rowY1, colHalf);
  y = field(pdf, "SA ID number", maskId(input.idNumber), margin + colHalf + 20, rowY1, colHalf);
  const rowY2 = y;
  field(pdf, "Phone", input.phone ? input.phone.replace(/(\d{3})\d+(\d{2})/, "$1 ••• $2") : "—", margin, rowY2, colHalf);
  y = field(pdf, "Occupation", input.occupation, margin + colHalf + 20, rowY2, colHalf);
  y = field(pdf, "Motivation", input.motivation, margin, y, colW);
  const rowY3 = y;
  field(pdf, "Contribution", input.contribution, margin, rowY3, colHalf);
  y = field(pdf, "Agreement version", input.agreementVersion, margin + colHalf + 20, rowY3, colHalf);

  y += 10;
  pdf.setDrawColor(220, 220, 220);
  pdf.line(margin, y, pageW - margin, y);
  y += 30;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  pdf.setTextColor(90, 90, 90);
  pdf.text("SIGNATURE", margin, y);
  pdf.setFont("helvetica", "italic");
  pdf.setFontSize(16);
  pdf.setTextColor(20, 20, 20);
  pdf.text(input.typedSignature, margin, y + 30);
  pdf.setDrawColor(150, 150, 150);
  pdf.line(margin, y + 42, margin + 220, y + 42);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(90, 90, 90);
  pdf.text(`Signed at: ${input.dateStr}`, margin, y + 58);

  y += 90;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);
  pdf.setTextColor(120, 120, 120);
  pdf.text(`Doc hash: ${input.docHash} · Method: ECT Act 25/2002 e-signature`, margin, y, { maxWidth: colW });

  drawFooter(pdf);
  return pdf.output("blob");
}
