export const MEMBER_CATEGORIES = [
  "Psychologists",
  "Coaches",
  "Attorneys",
  "Accountants",
  "Property Specialists",
  "Financial Advisors",
  "Medical Professionals",
  "Entrepreneurs",
  "Educators",
  "Marketing & PR",
  "Technology & Digital",
  "Creatives & Designers",
  "Consultants",
  "Healthcare & Wellness",
  "Hospitality & Events",
  "Retail & Fashion",
  "Construction & Trades",
  "Non Profit & Community",
  "Students",
  "Other",
] as const;
