/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as InfoRouteImport } from './routes/info'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminExportsRouteImport } from './routes/admin.exports'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as ApiPublicPayfastItnRouteImport } from './routes/api/public/payfast.itn'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPayfastItnRoute = ApiPublicPayfastItnRouteImport.update({
  id: '/api/public/payfast/itn',
  path: '/api/public/payfast/itn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/info': typeof InfoRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/team': typeof TeamRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payfast/itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/info': typeof InfoRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/team': typeof TeamRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/payfast/itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/info': typeof InfoRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/team': typeof TeamRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payfast/itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/events'
    | '/info'
    | '/membership'
    | '/news'
    | '/portal'
    | '/portfolio'
    | '/team'
    | '/admin/applications'
    | '/admin/billing'
    | '/admin/documents'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/members'
    | '/admin/messages'
    | '/admin/portfolio'
    | '/admin/settings'
    | '/admin/'
    | '/api/public/payfast/itn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/info'
    | '/membership'
    | '/news'
    | '/portal'
    | '/portfolio'
    | '/team'
    | '/admin/applications'
    | '/admin/billing'
    | '/admin/documents'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/members'
    | '/admin/messages'
    | '/admin/portfolio'
    | '/admin/settings'
    | '/admin'
    | '/api/public/payfast/itn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/events'
    | '/info'
    | '/membership'
    | '/news'
    | '/portal'
    | '/portfolio'
    | '/team'
    | '/admin/applications'
    | '/admin/billing'
    | '/admin/documents'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/members'
    | '/admin/messages'
    | '/admin/portfolio'
    | '/admin/settings'
    | '/admin/'
    | '/api/public/payfast/itn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  InfoRoute: typeof InfoRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRoute
  PortalRoute: typeof PortalRoute
  PortfolioRoute: typeof PortfolioRoute
  TeamRoute: typeof TeamRoute
  ApiPublicPayfastItnRoute: typeof ApiPublicPayfastItnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payfast/itn': {
      id: '/api/public/payfast/itn'
      path: '/api/public/payfast/itn'
      fullPath: '/api/public/payfast/itn'
      preLoaderRoute: typeof ApiPublicPayfastItnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  InfoRoute: InfoRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRoute,
  PortalRoute: PortalRoute,
  PortfolioRoute: PortfolioRoute,
  TeamRoute: TeamRoute,
  ApiPublicPayfastItnRoute: ApiPublicPayfastItnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
